[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "python build.py"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/products/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200